---

[node_servers]
node1 ansible_host=192.168.56.11 ansible_user=john
node2 ansible_host=192.168.56.12 ansible_user=john

[controller]
controller.srv.world

[nodes]
node1.srv.world
node2.srv.world

[all:vars]
ansible_user=john
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_become=yes
ansible_become_method=sudo

