---
# Resize LV (grow or shrink)
- name: Resize logical volume
  lvol:
    vg: "{{ lvm_vg }}"
    lv: "{{ lvm_lv }}"
    size: "{{ lvm_resize }}"
  when:
    - lvm_resize is defined
    - lvm_resize | length > 0

# Grow filesystem (XFS)
- name: Grow XFS filesystem
  command: xfs_growfs "{{ lvm_mount }}"
  when:
    - lvm_resize is defined
    - lvm_resize | length > 0
    - ansible_facts['filesystem'][lvm_mount]['fstype'] == "xfs"

# Shrink filesystem (EXT4 only)
- name: Shrink EXT4 filesystem
  command: resize2fs "{{ lvm_mount }}" "{{ lvm_resize }}"
  when:
    - lvm_resize is defined
    - lvm_resize | length > 0
    - ansible_facts['filesystem'][lvm_mount]['fstype'] == "ext4"

# Shrink LV (EXT4 only)
- name: Shrink logical volume (EXT4 only)
  lvol:
    vg: "{{ lvm_vg }}"
    lv: "{{ lvm_lv }}"
    size: "{{ lvm_resize }}"
  when:
    - lvm_resize is defined
    - lvm_resize | length > 0
    - ansible_facts['filesystem'][lvm_mount]['fstype'] == "ext4"

