---
timezone: "Europe/London"

baseline_packages:
  - vim
  - curl
  - wget
  - net-tools
  - tar
  - unzip
  - git

sysctl_settings:
  - { key: "net.ipv4.ip_forward", value: "1" }
  - { key: "vm.swappiness", value: "10" }